services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn test_run_01:app"
    envVars:
      - key: FLASK_ENV
        value: production
